[package]
name = "adesh-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
adesh-contracts = { path = "../adesh-contracts" }
async-trait.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
